# This config file is used by ros2_control for real hardware
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gantry_robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gantry_robot_controller:
  ros__parameters:
    joints:
      - joint_1_2
      - joint_2_3
      - joint_3_4
      - joint_4_5
      - joint_5_6
      - joint_6_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
